version: '2'
services:
  app:
    image: springcommunity/spring-petclinic-rest
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    mem_limit: 1024m
    environment:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
      SERVER_PORT: '8080'
      SPRING_SQL_INIT_MODE: always
      SPRING_PROFILES_ACTIVE: spring-data-jpa,postgresql
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
  app1:
    image: springcommunity/spring-petclinic-rest
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    cpuset: '0,1'
    mem_limit: 1024m
    environment:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
      SERVER_PORT: '8080'
      SPRING_SQL_INIT_MODE: always
      SPRING_PROFILES_ACTIVE: spring-data-jpa,postgresql
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
      SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: 20
      BPL_JVM_THREAD_COUNT: 60
  app2:
    image: springcommunity/spring-petclinic-rest
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    cpuset: '0,1,2,3'
    mem_limit: 1024m
    environment:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
      SERVER_PORT: '8080'
      SPRING_SQL_INIT_MODE: always
      SPRING_PROFILES_ACTIVE: spring-data-jpa,postgresql
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
      SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: 40
      BPL_JVM_THREAD_COUNT: 120
  app3:
    image: springcommunity/spring-petclinic-rest
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    cpuset: '0,1,2,3,4,5'
    mem_limit: 1024m
    environment:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
      SERVER_PORT: '8080'
      SPRING_SQL_INIT_MODE: always
      SPRING_PROFILES_ACTIVE: spring-data-jpa,postgresql
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
      SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: 60
      BPL_JVM_THREAD_COUNT: 180
  app4:
    image: springcommunity/spring-petclinic-rest
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    cpuset: '0,1,2,3,4,5,6,7'
    mem_limit: 1024m
    environment:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
      SERVER_PORT: '8080'
      SPRING_SQL_INIT_MODE: always
      SPRING_PROFILES_ACTIVE: spring-data-jpa,postgresql
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
      SPRING_DATASOURCE_HIKARI_MAXIMUMPOOLSIZE: 80
      BPL_JVM_THREAD_COUNT: 240
  postgres:
    image: postgres:13-alpine
    ports:
      - '5432'
    mem_limit: 512m
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
